apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vxzw48oif-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vxzw48oif-python 
  name: vxzw48oif-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vxzw48oif-python 
